//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pharma.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock()
        {
            this.StockIn = new HashSet<StockIn>();
            this.Vente = new HashSet<Vente>();
        }
    
        public int StockID { get; set; }
        public string NomArticle { get; set; }
        public string Description { get; set; }
        public Nullable<int> QuantiteTotale { get; set; }
        public Nullable<int> QuantiteVendue { get; set; }
        public Nullable<int> QuantiteDisponible { get; set; }
        public Nullable<decimal> PrixTotal { get; set; }
        public Nullable<decimal> PrixUnitaire { get; set; }
        public Nullable<System.DateTime> DateEntree { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockIn> StockIn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vente> Vente { get; set; }
    }
}
