//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pharma.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockIn
    {
        public int StockInID { get; set; }
        public string NomArticle { get; set; }
        public string Description { get; set; }
        public Nullable<int> QuantiteEntree { get; set; }
        public Nullable<decimal> PrixUnitaire { get; set; }
        public Nullable<int> EntrepriseID { get; set; }
        public Nullable<System.DateTime> DateExpiration { get; set; }
        public string LieuEntree { get; set; }
        public Nullable<System.DateTime> DateEntree { get; set; }
        public Nullable<int> StockID { get; set; }
    
        public virtual Entreprise Entreprise { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
