//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pharma.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateurs
    {
        public int UtilisateurID { get; set; }
        public string NomUtilisateur { get; set; }
        public string MotDePasse { get; set; }
        public string TypeUtilisateur { get; set; }
        public Nullable<System.DateTime> DateInscription { get; set; }
    }
}
