//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pharma.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vente
    {
        public int VenteID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string NomArticle { get; set; }
        public Nullable<decimal> PrixUnitaire { get; set; }
        public Nullable<int> QuantiteVendue { get; set; }
        public Nullable<decimal> PrixTotal { get; set; }
        public Nullable<System.DateTime> DateTransaction { get; set; }
        public Nullable<int> StockID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
